#! /bin/sh

$HOME/.config/bspwm/autostart.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

bspc config border_width         0
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
bspc config top_padding 40c

bspc rule -a discord desktop=5
bspc rule -a spotify desktop=6